server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: job-service
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    sqlScriptEncoding: UTF-8
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pz_job}
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT:180000}
      minimum-idle: ${DB_MINIMUM_IDLE:10}
      maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE:5000}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000}
      max-lifetime: ${DB_MAX_LIFETIME:1200000}
      auto-commit: ${DB_AUTO_COMMIT:true}
      dataSourceProperties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  liquibase:
    enabled: true
    database-change-log-table: id_databasechangelog
    database-change-log-lock-table: id_databasechangeloglock
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never # Default is 'always'
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: quartz-demo-app
#            instanceId: AUTO
#            instanceIdGenerator:
#              class: com.sample.app.generators.CustomQuartzInstanceIdGenerator
#          threadPool:
#            threadCount: 20
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            useProperties: true
#            misfireThreshold: 60000
#            tablePrefix: qrtz_
#            isClustered: true
#          plugin:
#            shutdownHook:
#              class: org.quartz.plugins.management.ShutdownHookPlugin
#              cleanShutdown: TRUE
